## Numpy array and basics

In [1]:
import numpy as np

### creating array from list

In [2]:
arr_1d = np.array([1,2,3,4,5])
print ("1D array: ", arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print ("2D array: ", arr_2d)

1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


### List vs numpy array

In [3]:
py_list = [1,2,3]
print("Python list multiplication", py_list * 2)

np_array = np.array([1,2,3]) # element wise multiplication
print("Python array multiplication", np_array * 2)

Python list multiplication [1, 2, 3, 1, 2, 3]
Python array multiplication [2 4 6]


### creating array from scratch

In [7]:
zeros = np.zeros((3,4))
print(" zeros array: \n", zeros)

ones = np.ones((3,2))
print(" one array: \n", ones)

full = np.full((2,2),7)
print(" full array: \n", full)

random = np.random.random((2,3))
print(" random array: \n", random)

sequence = np.arange(0,10,2)
print(" sequence array: \n", sequence)

 zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
 one array: 
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
 full array: 
 [[7 7]
 [7 7]]
 random array: 
 [[0.88492809 0.44252049 0.16946005]
 [0.18863611 0.84724877 0.28739109]]
 sequence array: 
 [0 2 4 6 8]


### Vector, Matrix and Tensor

In [9]:
vector = np.array([1,2,3,4])
print(" vector: \n", vector)

matrix = np.array([[1,2,3],
                   [4,5,6]])
print(" matrix: \n", matrix)

tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print(" tensor: \n", tensor)


 vector: 
 [1 2 3 4]
 matrix: 
 [[1 2 3]
 [4 5 6]]
 tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array properties

In [12]:
array = np.array([[1,2,3],
                [4,5,6]])
print("Shape ", array.shape)
print("Dimension ", array.ndim)
print("Size ", array.size)
print("Data type ", array.dtype)


Shape  (2, 3)
Dimension  2
Size  6
Data type  int64


### Array reshaping

In [16]:
arr = np.arange(12)
print("Original array \n", arr)

reshaped = arr.reshape((3,4))
print("\n Reshaped array \n", reshaped)

flattened = reshaped.flatten()
print("\n Flattened array \n", flattened)

# ravel (returns view, instead of copy)
raveled = reshaped.ravel()
print("\n Raveled array \n", raveled)

# Transpose
transpose = reshaped.T
print("Transposed array \n", transpose)


Original array 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Raveled array 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed array 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
